### ISSUE TITLE
GET fails "sometimes"

### ISSUE THREAD

**Issue by dh3wr** [dapnet-core/web#28]
Wenn man den Edit-Knopf in der "All User" liste drückt, wird immer eine der Anfragen
````
this.loadUserNames();
this.loadSubscriberNames();
this.loadSubscriberGroups();
this.loadTransmitterNames();
this.loadTransmitterGroups();
````
mit ``500`` beantwortet.
Auch wenn man ``this.loadSubscriberNames();`` mehrfach ausführt, ist einer dabei mit 500.

![grafik](https://user-images.githubusercontent.com/16710361/63704456-67ac3a00-c82b-11e9-9c99-dc9459a34215.png)

Reload der Edit-Seite http://44.225.164.51/#/users/edit/aprsclient1 geht aber immer.

Header sind aber gleich bei allen Anfragen:
````
GET /users/_usernames HTTP/1.1
Host: 44.225.164.51
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
Accept: application/json, text/plain, */*
Authorization: Basic XXXXXXXXXXXXXXXXXXXXXXXXXXXX
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36
Referer: http://44.225.164.51/
Accept-Encoding: gzip, deflate
Accept-Language: de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7
Cookie: JSESSIONID=1F86XXXXXXXXXXXXXXXXXXXXXXXX
````

**Comment by dh3wr** [comment]
Wenn nicht ``_usernames`` failed, dann ein anderer. Noch kein System erkennbar. Vielleicht zu viele Anfragen gleichzeitig?

**Comment by Taronyu** [comment]
Gibts im Log vom Database Service was zu sehen?

**Comment by Taronyu** [comment]
Wo ist der Code überhaupt? Ich habe mal im Repo gesucht, die Stelle mit dem this.loadSubscriberName() aber gar nicht finden können

**Comment by dh3wr** [comment]
@Taronyu Code ist hier
https://github.com/dapnet-core/web/blob/vuetify/src/components/user/New.vue Zeile 863 ff.

**Comment by dh3wr** [comment]
> Gibts im Log vom Database Service was zu sehen?
````
database_1     | 2019-08-28 08:17:37.279 ERROR 6 --- [p-nio-80-exec-4] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.web.client.HttpServerErrorException$InternalServerError: 500 Internal Server Error] with root cause
database_1     |
database_1     | org.springframework.web.client.HttpServerErrorException$InternalServerError: 500 Internal Server Error
database_1     |        at org.springframework.web.client.HttpServerErrorException.create(HttpServerErrorException.java:79) ~[spring-web-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
database_1     |        at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:124) ~[spring-web-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
database_1     |        at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:102) ~[spring-web-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
database_1     |        at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63) ~[spring-web-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
database_1     |        at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:777) ~[spring-web-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
database_1     |        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:735) ~[spring-web-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
database_1     |        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:669) ~[spring-web-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
database_1     |        at org.springframework.web.client.RestTemplate.getForObject(RestTemplate.java:310) ~[spring-web-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
database_1     |        at de.hampager.dapnet.service.database.controller.UserController.getUsernames(UserController.java:98) ~[classes!/:0.0.11-SNAPSHOT]
database_1     |        at jdk.internal.reflect.GeneratedMethodAccessor113.invoke(Unknown Source) ~[na:na]
database_1     |        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
database_1     |        at java.base/java.lang.reflect.Method.invoke(Method.java:564) ~[na:na]
database_1     |        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:189) ~[spring-web-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
database_1     |        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138) ~[spring-web-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
database_1     |        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102) ~[spring-webmvc-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
database_1     |        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895) ~[spring-webmvc-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
database_1     |        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:800) ~[spring-webmvc-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
database_1     |        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
database_1     |        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1038) ~[spring-webmvc-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
database_1     |        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942) ~[spring-webmvc-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
database_1     |        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005) ~[spring-webmvc-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
database_1     |        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:897) ~[spring-webmvc-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
database_1     |        at javax.servlet.http.HttpServlet.service(HttpServlet.java:634) ~[tomcat-embed-core-9.0.13.jar!/:9.0.13]
database_1     |        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:882) ~[spring-webmvc-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
database_1     |        at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) ~[tomcat-embed-core-9.0.13.jar!/:9.0.13]
database_1     |        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[tomcat-embed-core-9.0.13.jar!/:9.0.13]
database_1     |        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.13.jar!/:9.0.13]
database_1     |        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-embed-websocket-9.0.13.jar!/:9.0.13]
database_1     |        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.13.jar!/:9.0.13]
database_1     |        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.13.jar!/:9.0.13]
database_1     |        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:320) ~[spring-security-web-5.1.2.RELEASE.jar!/:5.1.2.RELEASE]
database_1     |        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127) ~[spring-security-web-5.1.2.RELEASE.jar!/:5.1.2.RELEASE]
database_1     |        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91) ~[spring-security-web-5.1.2.RELEASE.jar!/:5.1.2.RELEASE]
database_1     |        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.1.2.RELEASE.jar!/:5.1.2.RELEASE]
database_1     |        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:119) ~[spring-security-web-5.1.2.RELEASE.jar!/:5.1.2.RELEASE]
database_1     |        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.1.2.RELEASE.jar!/:5.1.2.RELEASE]
database_1     |        at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137) ~[spring-security-web-5.1.2.RELEASE.jar!/:5.1.2.RELEASE]
database_1     |        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.1.2.RELEASE.jar!/:5.1.2.RELEASE]
database_1     |        at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111) ~[spring-security-web-5.1.2.RELEASE.jar!/:5.1.2.RELEASE]
database_1     |        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.1.2.RELEASE.jar!/:5.1.2.RELEASE]
database_1     |        at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:170) ~[spring-security-web-5.1.2.RELEASE.jar!/:5.1.2.RELEASE]
database_1     |        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.1.2.RELEASE.jar!/:5.1.2.RELEASE]
database_1     |        at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63) ~[spring-security-web-5.1.2.RELEASE.jar!/:5.1.2.RELEASE]
database_1     |        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.1.2.RELEASE.jar!/:5.1.2.RELEASE]
database_1     |        at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilterInternal(BasicAuthenticationFilter.java:215) ~[spring-security-web-5.1.2.RELEASE.jar!/:5.1.2.RELEASE]
database_1     |        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
database_1     |        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.1.2.RELEASE.jar!/:5.1.2.RELEASE]
database_1     |        at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116) ~[spring-security-web-5.1.2.RELEASE.jar!/:5.1.2.RELEASE]
database_1     |        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.1.2.RELEASE.jar!/:5.1.2.RELEASE]
database_1     |        at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:74) ~[spring-security-web-5.1.2.RELEASE.jar!/:5.1.2.RELEASE]
database_1     |        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
database_1     |        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.1.2.RELEASE.jar!/:5.1.2.RELEASE]
database_1     |        at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105) ~[spring-security-web-5.1.2.RELEASE.jar!/:5.1.2.RELEASE]
database_1     |        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.1.2.RELEASE.jar!/:5.1.2.RELEASE]
database_1     |        at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56) ~[spring-security-web-5.1.2.RELEASE.jar!/:5.1.2.RELEASE]
database_1     |        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
database_1     |        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.1.2.RELEASE.jar!/:5.1.2.RELEASE]
database_1     |        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215) ~[spring-security-web-5.1.2.RELEASE.jar!/:5.1.2.RELEASE]
database_1     |        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178) ~[spring-security-web-5.1.2.RELEASE.jar!/:5.1.2.RELEASE]
database_1     |        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:357) ~[spring-web-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
database_1     |        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:270) ~[spring-web-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
database_1     |        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.13.jar!/:9.0.13]
database_1     |        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.13.jar!/:9.0.13]
database_1     |        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99) ~[spring-web-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
database_1     |        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
database_1     |        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.13.jar!/:9.0.13]
database_1     |        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.13.jar!/:9.0.13]
database_1     |        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:92) ~[spring-web-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
database_1     |        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
database_1     |        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.13.jar!/:9.0.13]
database_1     |        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.13.jar!/:9.0.13]
database_1     |        at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93) ~[spring-web-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
database_1     |        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
database_1     |        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.13.jar!/:9.0.13]
database_1     |        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.13.jar!/:9.0.13]
database_1     |        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200) ~[spring-web-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
database_1     |        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
database_1     |        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.13.jar!/:9.0.13]
database_1     |        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.13.jar!/:9.0.13]
database_1     |        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199) ~[tomcat-embed-core-9.0.13.jar!/:9.0.13]
database_1     |        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat-embed-core-9.0.13.jar!/:9.0.13]
database_1     |        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490) [tomcat-embed-core-9.0.13.jar!/:9.0.13]
database_1     |        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [tomcat-embed-core-9.0.13.jar!/:9.0.13]
database_1     |        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [tomcat-embed-core-9.0.13.jar!/:9.0.13]
database_1     |        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [tomcat-embed-core-9.0.13.jar!/:9.0.13]
database_1     |        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [tomcat-embed-core-9.0.13.jar!/:9.0.13]
database_1     |        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408) [tomcat-embed-core-9.0.13.jar!/:9.0.13]
database_1     |        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-embed-core-9.0.13.jar!/:9.0.13]
database_1     |        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:791) [tomcat-embed-core-9.0.13.jar!/:9.0.13]
database_1     |        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1417) [tomcat-embed-core-9.0.13.jar!/:9.0.13]
database_1     |        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-9.0.13.jar!/:9.0.13]
database_1     |        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135) [na:na]
database_1     |        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [na:na]
database_1     |        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-9.0.13.jar!/:9.0.13]
database_1     |        at java.base/java.lang.Thread.run(Thread.java:844) [na:na]
database_1     |
````

**Comment by dh3wr** [comment]
Logs können so erhalten werden:
dapnetdc2.db0sda.ampr.org rwth-afu -> you_know -> su -> you_know
``root@dapnetdc2:~/core# docker-compose logs -f database``

**Comment by dh3wr** [comment]
Es kommt von der CouchDB: Hier das Log, wenn der Fehler auftritt: Wie man sieht, geht der erste Aufruf schief.
````
couchdb_1      | [info] 2019-08-29T20:44:06.330377Z nonode@nohost <0.17775.1847> -------- OS Process #Port<0.2435359> Log :: function raised error: (new TypeError("req.headers is undefined", "./share/server/main.js", 766))
couchdb_1      | stacktrace: runProvides("noproc",[object Object])@./share/server/main.js:766
couchdb_1      | runList(function () {provides("json", function () {var usernames = [];while ((row = getRow())) {if (row.value) {usernames.push(row.id);}}send(JSON.stringify(usernames));});},[object Object],[object Array])@./share/server/main.js:1001
couchdb_1      | (function () {provides("json", function () {var usernames = [];while ((row = getRow())) {if (row.value) {usernames.push(row.id);}}send(JSON.stringify(usernames));});},[object Object],[object Array])@./share/server/main.js:1064
couchdb_1      | ("_design/users",[object Array],[object Array])@./share/server/main.js:1537
couchdb_1      | ()@./share/server/main.js:1582
couchdb_1      | ()@./share/server/main.js:1603
couchdb_1      | @./share/server/main.js:1
couchdb_1      |
couchdb_1      | [error] 2019-08-29T20:44:06.331480Z nonode@nohost <0.17058.6726> 1d95cb96ae OS Process Error <0.17775.1847> :: {<<"render_error">>,<<"function raised error: (new TypeError(\"req.headers is undefined\", \"./share/server/main.js\", 766)) \nstacktrace: runProvides(\"noproc\",[object Object])@./share/server/main.js:766\nrunList(function () {provides(\"json\", function () {var usernames = [];while ((row = getRow())) {if (row.value) {usernames.push(row.id);}}send(JSON.stringify(usernames));});},[object Object],[object Array])@./share/server/main.js:1001\n(function () {provides(\"json\", function () {var usernames = [];while ((row = getRow())) {if (row.value) {usernames.push(row.id);}}send(JSON.stringify(usernames));});},[object Object],[object Array])@./share/server/main.js:1064\n(\"_design/users\",[object Array],[object Array])@./share/server/main.js:1537\n()@./share/server/main.js:1582\n()@./share/server/main.js:1603\n@./share/server/main.js:1\n">>}
couchdb_1      | [notice] 2019-08-29T20:44:06.332099Z nonode@nohost <0.17058.6726> 1d95cb96ae couchdb:5984 172.18.0.8 admin GET /users/_design/users/_list/usernames/byId?reduce=false 500 ok 12
couchdb_1      | [notice] 2019-08-29T20:44:06.385982Z nonode@nohost <0.17058.6726> f2866d2054 couchdb:5984 172.18.0.8 admin GET /subscribers/_design/subscribers/_list/names/byId?reduce=false 200 ok 37
couchdb_1      | [notice] 2019-08-29T20:44:06.441711Z nonode@nohost <0.1752.6732> 79e080ed4f couchdb:5984 172.18.0.8 admin GET /users/aprsclient1 200 ok 19
couchdb_1      | [notice] 2019-08-29T20:44:06.461223Z nonode@nohost <0.16132.6731> e229ef4c58 couchdb:5984 172.18.0.8 admin GET /transmitters/_design/transmitters/_list/names/byId?reduce=false 200 ok 60
couchdb_1      | [notice] 2019-08-29T20:44:06.470369Z nonode@nohost <0.8070.6730> b21be1eddf couchdb:5984 172.18.0.8 admin GET /subscribers/_design/subscribers/_list/groups/byGroup?group_level=5 200 ok 49
couchdb_1      | [notice] 2019-08-29T20:44:06.484726Z nonode@nohost <0.32263.6730> d940a172a3 couchdb:5984 172.18.0.8 admin GET /transmitters/_design/transmitters/_list/groups/byGroup?group_level=5 200 ok 64
````

**Comment by dh3wr** [comment]
Ein Reload der Seite gibt aber bei exakt dem gleichen Aufruf Erfolg mit 200:
````
couchdb_1      | [notice] 2019-08-29T20:47:28.914519Z nonode@nohost <0.22513.6731> f31058cf8f couchdb:5984 172.18.0.8 admin GET /users/_design/users/_list/usernames/byId?reduce=false 200 ok 57
````

**Comment by dh3wr** [comment]
Logs können so erhalten werden:
dapnetdc2.db0sda.ampr.org rwth-afu -> you_know -> su -> you_know
``root@dapnetdc2:~/core# docker-compose logs -f database``

**Comment by dh3wr** [comment]
Update von CouchDB durch @7h0ma5 hat das Problem behoben. Bitte auch auf dc3 nachziehen, @7h0ma5 . Danke
